"""Release and processing-engine version identifiers."""

PLUGIN_VERSION = "0.3.0-rc1"
PS_MAP_ENGINE_VERSION = "0.1.2"
GEOMETRY_ENGINE_VERSION = "m10.0"
SAR_PROCESSING_ENGINE_VERSION = "m10.0"
SAR_MAP_ENGINE_VERSION = "m53.2"
DISPLACEMENT_BATCH_ENGINE_VERSION = "m7.2.2.1"
TIMESERIES_REVIEW_ENGINE_VERSION = "m9.0.0"
